BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "GROUP" (
	"ID"	INTEGER,
	"NAME"	TEXT NOT NULL,
	"LVL"	INTEGER NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "USER" (
	"ID"	INTEGER,
	"GROUP_ID"	INTEGER,
	"NOM"	TEXT NOT NULL,
	"PRENOM"	TEXT NOT NULL,
	"EMAIL"	TEXT NOT NULL UNIQUE,
	"NUMEROMOBIL"	TEXT,
	"LANGUE"	TEXT,
	"MDP"	TEXT NOT NULL,
	"ACTIVER"	BOOLEAN DEFAULT 0,
	"TOKEN"	TEXT,
	PRIMARY KEY("ID" AUTOINCREMENT),
	FOREIGN KEY("GROUP_ID") REFERENCES "GROUP"("ID") ON DELETE SET NULL
);
CREATE TABLE IF NOT EXISTS "MESSAGE" (
	"ID"	INTEGER,
	"ORIGIN_USER_ID"	INTEGER NOT NULL,
	"DESTINATION_USER_ID"	INTEGER NOT NULL,
	"MESSAGE"	TEXT NOT NULL,
	"DATEHEUR"	DATETIME DEFAULT CURRENT_TIMESTAMP,
	"LUE"	BOOLEAN DEFAULT 0,
	PRIMARY KEY("ID" AUTOINCREMENT),
	FOREIGN KEY("DESTINATION_USER_ID") REFERENCES "USER"("ID") ON DELETE CASCADE,
	FOREIGN KEY("ORIGIN_USER_ID") REFERENCES "USER"("ID") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "SMTP_CONFIG" (
	"ID"	INTEGER,
	"HOST"	TEXT NOT NULL,
	"PORT"	INTEGER NOT NULL,
	"SECURE"	TEXT NOT NULL,
	"USERNAME"	TEXT NOT NULL,
	"PASSWORD"	TEXT NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "CONTACT" (
	"ID"	INTEGER,
	"NOM"	TEXT NOT NULL,
	"PRENOM"	TEXT NOT NULL,
	"EMAIL"	TEXT NOT NULL,
	"CERTIFICAT"	TEXT,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "SERVICE" (
	"ID"	INTEGER,
	"NOM"	TEXT NOT NULL,
	"DESCRIPTION"	TEXT,
	"IMAGE"	TEXT,
	"ACTIF"	BOOLEAN DEFAULT 1,
	"VISIBILITE_MIN"	INTEGER DEFAULT 0,
	"ORDRE"	INTEGER DEFAULT 0,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
COMMIT;
